# Generated by Django 6.0 on 2025-12-13 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0003_school_school_admin'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='schools.school')),
            ],
            options={
                'verbose_name': 'Rôle Personnalisé',
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customrole', verbose_name='Rôle Personnalisé'),
        ),
    ]
