# Generated by Django 6.0 on 2025-12-22 21:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0007_rename_academicperiod_school_academic_period'),
        ('users', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customrole',
            options={'ordering': ['name'], 'verbose_name': 'Rôle Personnalisé', 'verbose_name_plural': 'Rôles Personnalisés'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterUniqueTogether(
            name='customrole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customrole',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email vérifié'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du rôle'),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_roles', to='auth.permission', verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.customrole', verbose_name='Rôle Personnalisé'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='schools.school'),
        ),
        migrations.RemoveField(
            model_name='customrole',
            name='school',
        ),
        migrations.CreateModel(
            name='UserCustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='users.customrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attribution de Rôle',
                'verbose_name_plural': 'Attributions de Rôles',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
