# Generated by Django 6.0 on 2025-12-23 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_alter_customrole_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie de Permissions',
                'verbose_name_plural': 'Catégories de Permissions',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('module', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('is_dangerous', models.BooleanField(default=False)),
                ('default_groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('django_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.permission')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.permissioncategory')),
            ],
            options={
                'verbose_name': 'Permission Personnalisée',
                'verbose_name_plural': 'Permissions Personnalisées',
                'ordering': ['category__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('VIEW', 'Voir seulement'), ('CREATE', 'Créer'), ('UPDATE', 'Modifier'), ('DELETE', 'Supprimer'), ('APPROVE', 'Approuver'), ('MANAGE', 'Gérer complètement'), ('FULL', 'Accès complet')], default='VIEW', max_length=20)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.custompermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.customrole')),
            ],
            options={
                'verbose_name': 'Permission de Rôle',
                'verbose_name_plural': 'Permissions de Rôle',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
