# Generated by Django 6.0 on 2025-12-23 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_rename_academicperiod_school_academic_period'),
        ('users', '0006_permissioncategory_permissionfeature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrole',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='schools.school'),
        ),
    ]
