# Generated by Django 6.0 on 2025-12-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customrole_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('school_admin', 'Admin École'), ('staff', 'Personnel'), ('teacher', 'Enseignant'), ('parent', 'Parent'), ('student', 'Élève')], max_length=20),
        ),
    ]
