# Generated by Django 6.0 on 2026-01-02 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0008_schoolmembership_schoolroleassignment'),
        ('users', '0010_user_approved_at_user_approved_by_user_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customrole',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='customrole',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du rôle'),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_roles', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='schools.school'),
        ),
        migrations.AlterUniqueTogether(
            name='customrole',
            unique_together={('name', 'school')},
        ),
    ]
