# Generated by Django 6.0 on 2026-01-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0008_schoolmembership_schoolroleassignment'),
        ('users', '0011_alter_customrole_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customrole',
            options={'ordering': ['name'], 'verbose_name': 'Rôle Personnalisé', 'verbose_name_plural': 'Rôles Personnalisés'},
        ),
        migrations.AlterUniqueTogether(
            name='customrole',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='custom_role',
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du rôle'),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_roles', to='auth.permission', verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='schools.school'),
        ),
    ]
