# Generated by Django 6.0 on 2026-01-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customrole_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Forcer le changement de mot de passe au premier login'),
        ),
    ]
