# Generated by Django 6.0 on 2026-01-07 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0014_alter_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PermissionFeature',
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='post_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Post-nom'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_roles', to='auth.permission', verbose_name='Permissions Django'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='usercustomrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercustomrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
