# Generated by Django 6.0 on 2026-01-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_permissionfeature_alter_rolepermission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('school_admin', 'Admin École'), ('school_user', 'Utilisateur École'), ('staff', 'Personnel'), ('teacher', 'Enseignant'), ('parent', 'Parent'), ('student', 'Élève')], max_length=20),
        ),
    ]
