# Generated by Django 6.0 on 2026-01-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('school_admin', 'Admin École'), ('school_user', 'Utilisateur École'), ('staff', 'Personnel'), ('teacher', 'Enseignant'), ('parent', 'Parent'), ('student', 'Élève')], default='teacher', max_length=20),
        ),
    ]
