# Generated by Django 6.0 on 2025-12-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('schools', '0005_remove_school_academic_year_school_academicperiod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicYear',
        ),
    ]
