# Generated by Django 6.0 on 2026-01-06 07:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AcademicPeriod', '0002_initial'),
        ('academia', '0002_remove_course_credits_remove_course_weight_and_more'),
        ('schools', '0008_schoolmembership_schoolroleassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='expenses/')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('PAID', 'Payé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AcademicPeriod.academicperiod', verbose_name='Année Fiscale')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'verbose_name': 'Dépense',
            },
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='CODE unique (ex: SCO, BUS) pour reporting', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK', 'Banque')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Validé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('mobile_operator', models.CharField(blank=True, help_text='Orange, Airtel, Vodacom', max_length=50, null=True)),
                ('transaction_ref', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transaction Réseau')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('academic_period', models.ForeignKey(limit_choices_to={'type': 'YEAR'}, on_delete=django.db.models.deletion.PROTECT, to='AcademicPeriod.academicperiod', verbose_name='Année Fiscale')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.feecategory', verbose_name='Motif')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant unitaire (ex: 100$)', max_digits=10)),
                ('frequency', models.CharField(choices=[('ANNUAL', 'Paiement Unique (Annuel)'), ('TRIMESTER', 'Par Trimestre (x3)'), ('MONTHLY', 'Mensuel (x10)')], default='ANNUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_period', models.ForeignKey(limit_choices_to={'type': 'YEAR'}, on_delete=django.db.models.deletion.CASCADE, to='AcademicPeriod.academicperiod', verbose_name='Année Académique')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.feecategory')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.classe', verbose_name='Classe concernée')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'verbose_name': 'Configuration des Frais',
                'unique_together': {('classe', 'category', 'academic_period')},
            },
        ),
    ]
