# Generated by Django 6.0 on 2026-01-28 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AcademicPeriod', '0002_initial'),
        ('academia', '0008_remove_gradingperiod_is_exam_classe_system_type_and_more'),
        ('pupils', '0004_alter_enrollment_unique_together_and_more'),
        ('schools', '0008_schoolmembership_schoolroleassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='schools.school')),
            ],
            options={
                'verbose_name': 'Type de Frais',
                'verbose_name_plural': 'Types de Frais',
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant en devise principale', max_digits=12)),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'Paiement Unique (Annuel)'), ('TRIMESTER', 'Par Trimestre'), ('MONTHLY', 'Mensuel'), ('OCCASIONAL', 'Ponctuel')], default='TRIMESTER', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('academic_period', models.ForeignKey(blank=True, help_text='Optionnel : période spécifique', null=True, on_delete=django.db.models.deletion.SET_NULL, to='AcademicPeriod.academicperiod')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academia.classe')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='schools.school')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='finance.feetype')),
            ],
            options={
                'verbose_name': 'Structure de Frais',
                'verbose_name_plural': 'Structures de Frais',
            },
        ),
        migrations.CreateModel(
            name='FinanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_currency', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=2800, help_text='1 USD = ? CDF', max_digits=10)),
                ('expense_approval_threshold', models.DecimalField(decimal_places=2, default=50.0, help_text='Montant max sans validation de la direction', max_digits=12)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_config', to='schools.school')),
            ],
            options={
                'verbose_name': 'Configuration Financière',
                'verbose_name_plural': 'Configurations Financières',
            },
        ),
        migrations.CreateModel(
            name='StudentExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reason', models.TextField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exemptions', to=settings.AUTH_USER_MODEL)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemptions', to='finance.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemptions', to='pupils.student')),
            ],
            options={
                'verbose_name': 'Exonération Élève',
                'verbose_name_plural': 'Exonérations Élèves',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Entrée (Paiement élève)'), ('EXPENSE', 'Dépense')], max_length=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('BANK', 'Virement Bancaire'), ('MOBILE', 'Mobile Money')], default='CASH', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3)),
                ('exchange_rate_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_in_base_currency', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audited_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('AUDITED', 'Audité'), ('APPROVED', 'Validé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('audited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_audited', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
                ('fee_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.feestructure')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='schools.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='pupils.student')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('previous_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_approved', models.BooleanField(help_text='Null = En attente', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Demande de Correction',
                'verbose_name_plural': 'Demandes de Correction',
                'ordering': ['-created_at'],
            },
        ),
    ]
