# Generated by Django 6.0 on 2026-02-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_feetype_created_by_feetype_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='exchange_rate_used',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
