# Generated by Django 6.0 on 2025-12-15 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AcademicPeriod', '0002_initial'),
        ('schools', '0006_school_school_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du Cours')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code du Cours')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description du Cours')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Pondération du cours')),
                ('credits', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Crédits ECTS/Unités')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schools.school', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['school__name', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('PRIMARY', 'Primaire'), ('SECONDARY', 'Secondaire'), ('UNIVERSITY', 'Universitaire'), ('OTHER', 'Autre')], default='SECONDARY', max_length=15, verbose_name="Niveau d'Éducation")),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la Classe')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_in_period', to='AcademicPeriod.academicperiod', verbose_name='Période Académique')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school', verbose_name='École')),
                ('titulaire', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titular_of_classes', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant Titulaire')),
                ('courses', models.ManyToManyField(blank=True, related_name='classes', to='academia.course', verbose_name='Cours de la classe')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['school__name', 'academic_period__name', 'name'],
                'unique_together': {('name', 'academic_period', 'school')},
            },
        ),
    ]
