# Generated by Django 6.0 on 2025-12-15 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='weight',
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Coefficient/Pondération')),
                ('is_evaluative', models.BooleanField(default=True, verbose_name='Évaluatif')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academia.classe', verbose_name='Classe Assignée')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academia.course', verbose_name='Cours Assigné')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_loads', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant Responsable')),
            ],
            options={
                'verbose_name': 'Assignation Pédagogique',
                'verbose_name_plural': 'Assignations Pédagogiques',
                'ordering': ['classe__name', 'course__name'],
                'unique_together': {('classe', 'course')},
            },
        ),
    ]
