# Generated by Django 6.0 on 2026-01-07 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_alter_classe_titulaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='titulaire',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titular_of_classes', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant Titulaire'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_loads', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant Responsable'),
        ),
    ]
