# Generated by Django 6.0 on 2026-01-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicPeriod', '0002_initial'),
        ('academia', '0006_gradechangerequest'),
        ('schools', '0008_schoolmembership_schoolroleassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['school__name', 'academic_period__name', 'education_level', 'name'], 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('name', 'education_level', 'academic_period', 'school')},
        ),
    ]
