# Generated by Django 6.0 on 2026-01-25 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0007_alter_classe_options_alter_classe_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingperiod',
            name='is_exam',
        ),
        migrations.AddField(
            model_name='classe',
            name='system_type',
            field=models.CharField(choices=[('TRIMESTER', 'Trimestriel (ex: Primaire - 3 Cycles)'), ('SEMESTER', 'Semestriel (ex: Secondaire - 2 Cycles)')], default='SEMESTER', max_length=15, verbose_name='Système de division'),
        ),
        migrations.AddField(
            model_name='gradingperiod',
            name='category',
            field=models.CharField(choices=[('ROOT', 'Cycle Principal (Trimestre/Semestre)'), ('PERIOD', 'Période de cours (P1, P2...)'), ('EXAM', "Session d'Examen")], default='PERIOD', max_length=10, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='gradingperiod',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_periods', to='academia.gradingperiod', verbose_name='Période Parente (Cycle)'),
        ),
        migrations.AlterField(
            model_name='gradingperiod',
            name='end_date',
            field=models.DateField(verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='gradingperiod',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom (ex: Trimestre 1 ou Période 1)'),
        ),
        migrations.AlterField(
            model_name='gradingperiod',
            name='sequence_order',
            field=models.PositiveIntegerField(default=1, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='gradingperiod',
            name='start_date',
            field=models.DateField(verbose_name='Début'),
        ),
    ]
