# Generated by Django 6.0 on 2026-01-30 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicPeriod', '0002_initial'),
        ('academia', '0008_remove_gradingperiod_is_exam_classe_system_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='academic_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='AcademicPeriod.academicperiod'),
            preserve_default=False,
        ),
    ]
