# Generated by Django 6.0 on 2026-01-30 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicPeriod', '0002_initial'),
        ('academia', '0009_course_academic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='academic_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='AcademicPeriod.academicperiod'),
        ),
    ]
