# Generated by Django 6.0 on 2026-01-09 20:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AcademicPeriod', '0002_initial'),
        ('academia', '0004_alter_classe_titulaire_and_more'),
        ('schools', '0008_schoolmembership_schoolroleassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Post-nom')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Homme'), ('Female', 'Femme'), ('Other', 'Autre')], max_length=10, null=True)),
                ('student_id_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('dropped', 'Abandonné')], default='active', max_length=20)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
                ('academic_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AcademicPeriod.academicperiod')),
                ('current_classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academia.classe')),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('completed', 'Terminé'), ('withdrawn', 'Abandonné')], default='active', max_length=20)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademicPeriod.academicperiod')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.classe')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='pupils.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'last_name', 'middle_name', 'first_name', 'date_of_birth'), name='unique_student_identity_per_school'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'academic_period')},
        ),
    ]
