# Generated by Django 6.0 on 2026-01-05 17:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AcademicPeriod', '0002_initial'),
        ('academia', '0002_remove_course_credits_remove_course_weight_and_more'),
        ('schools', '0008_schoolmembership_schoolroleassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Post-nom')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Masculin'), ('female', 'Féminin'), ('other', 'Autre')], max_length=10, null=True, verbose_name='Genre')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('student_id_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matricule élève')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('dropout', 'Abandonné')], default='active', max_length=20, verbose_name='Statut')),
                ('is_active', models.BooleanField(default=True, help_text='Désactiver sans supprimer', verbose_name='Compte actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AcademicPeriod.academicperiod', verbose_name='Période académique')),
                ('current_classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academia.classe', verbose_name='Classe actuelle')),
                ('parents', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'parent'}, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Parents / Tuteurs')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='schools.school', verbose_name='École')),
                ('user_account', models.OneToOneField(blank=True, limit_choices_to={'user_type': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur élève')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['last_name', 'middle_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='pupils_stud_last_na_5aa2cb_idx'), models.Index(fields=['student_id_code'], name='pupils_stud_student_ef0915_idx'), models.Index(fields=['status'], name='pupils_stud_status_0b7d53_idx')],
            },
        ),
    ]
