# Generated by Django 6.0 on 2026-01-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='pupils_stud_last_na_5aa2cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='pupils_stud_student_ef0915_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='pupils_stud_status_0b7d53_idx',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
