# Generated by Django 6.0 on 2026-01-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
    ]
