# Generated by Django 6.0 on 2026-01-26 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicPeriod', '0002_initial'),
        ('academia', '0008_remove_gradingperiod_is_exam_classe_system_type_and_more'),
        ('pupils', '0003_alter_student_enrollment_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'classe', 'academic_period')},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.course'),
        ),
    ]
