# Generated by Django 6.0 on 2025-12-22 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0006_school_school_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du Plan')),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(blank=True, default='PLAN-001', max_length=20, unique=True, verbose_name='Code du plan')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix par unité')),
                ('duration_unit', models.CharField(choices=[('MONTH', 'Mois'), ('YEAR', 'An'), ('QUARTER', 'Trimestre')], default='MONTH', max_length=10)),
                ('duration_value', models.IntegerField(default=1, verbose_name="Durée (nombre d'unités)")),
                ('max_users', models.PositiveIntegerField(default=50, verbose_name='Quota max. Utilisateurs')),
                ('max_students', models.PositiveIntegerField(default=200, verbose_name='Quota max. Étudiants')),
                ('max_storage_gb', models.PositiveIntegerField(default=10, verbose_name='Stockage (GB)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Plan Actif')),
                ('is_public', models.BooleanField(default=True, verbose_name='Visible publiquement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Plan d'Abonnement",
                'verbose_name_plural': "Plans d'Abonnement",
            },
        ),
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code du module')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du module')),
                ('description', models.TextField(blank=True)),
                ('module_type', models.CharField(choices=[('ACADEMIC', 'Académique'), ('FINANCE', 'Finance/Comptabilité'), ('HR', 'Ressources Humaines'), ('COMMUNICATION', 'Communication'), ('ADMIN', 'Administration')], default='ACADEMIC', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif dans le système')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône Lucide", max_length=100)),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Module Système',
                'verbose_name_plural': 'Modules Système',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de Début')),
                ('end_date', models.DateField(verbose_name='Date de Fin')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renouvellement automatique')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('PENDING', 'En attente'), ('SUSPENDED', 'Suspendu'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
                ('current_users', models.PositiveIntegerField(default=0, verbose_name='Utilisateurs actuels')),
                ('current_students', models.PositiveIntegerField(default=0, verbose_name='Étudiants actuels')),
                ('storage_used_gb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Stockage utilisé (GB)')),
                ('is_notified_expiry', models.BooleanField(default=False)),
                ('last_notification_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=uuid.uuid4, max_length=50, unique=True, verbose_name='Référence')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='schools.school')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': "Abonnement d'École",
                'verbose_name_plural': "Abonnements d'Écoles",
            },
        ),
        migrations.CreateModel(
            name='SchoolModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('activated_date', models.DateField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('school_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.schoolsubscription')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.systemmodule')),
            ],
            options={
                'verbose_name': 'Accès Module École',
                'verbose_name_plural': 'Accès Modules Écoles',
                'unique_together': {('school_subscription', 'module')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Devise')),
                ('payment_method', models.CharField(choices=[('MTN_MONEY', 'MTN Money'), ('AIRTM', 'Airtel Money'), ('ORANGE', 'Orange Money'), ('VISA', 'Carte Visa/Mastercard'), ('BANK', 'Virement Bancaire'), ('CASH', 'Espèces')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='ID Transaction')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('school_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.schoolsubscription')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('issue_date', models.DateField(verbose_name="Date d'émission")),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant TVA')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyée'), ('PAID', 'Payée'), ('OVERDUE', 'En retard'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/', verbose_name='Fichier PDF')),
                ('school_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscriptions.schoolsubscription')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='PlanModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('BASIC', 'Accès de base'), ('STANDARD', 'Accès standard'), ('PREMIUM', 'Accès premium'), ('FULL', 'Accès complet')], default='STANDARD', max_length=20)),
                ('is_included', models.BooleanField(default=True, verbose_name='Inclus dans le plan')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Fonctionnalités spécifiques')),
                ('order', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.systemmodule')),
            ],
            options={
                'verbose_name': 'Module de Plan',
                'verbose_name_plural': 'Modules de Plan',
                'ordering': ['order'],
                'unique_together': {('plan', 'module')},
            },
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='included_modules',
            field=models.ManyToManyField(related_name='included_in_plans', through='subscriptions.PlanModule', to='subscriptions.systemmodule'),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='activated_modules',
            field=models.ManyToManyField(related_name='active_in_schools', through='subscriptions.SchoolModuleAccess', to='subscriptions.systemmodule'),
        ),
    ]
