# Generated by Django 6.0 on 2025-12-13 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name="Nom de l'École")),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code unique')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspendue'), ('EXPIRED', 'Abonnement expiré')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/')),
                ('max_students', models.PositiveIntegerField(default=0)),
                ('max_staff', models.PositiveIntegerField(default=0)),
                ('max_teachers', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='core.academicyear', verbose_name='Année académique active')),
            ],
            options={
                'verbose_name': 'École',
                'verbose_name_plural': 'Écoles',
                'ordering': ['name'],
            },
        ),
    ]
