# Generated by Django 6.0 on 2025-12-14 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('schools', '0003_school_school_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='core.academicyear', verbose_name='Année académique active'),
        ),
    ]
