# Generated by Django 6.0 on 2025-12-14 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicPeriod', '0002_initial'),
        ('schools', '0004_alter_school_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='school',
            name='AcademicPeriod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='AcademicPeriod.academicperiod', verbose_name='Année académique active'),
        ),
    ]
