# Generated by Django 6.0 on 2025-12-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_remove_school_academic_year_school_academicperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('PRI', 'Primaire'), ('SEC', 'Secondaire'), ('MIX', 'Mixte (Primaire et Secondaire)'), ('UNI', 'Université')], default='SEC', help_text="Définit si l'école est primaire, secondaire, mixte ou universitaire.", max_length=3, verbose_name="Type d'École"),
        ),
    ]
