# Generated by Django 6.0 on 2025-12-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_school_school_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='AcademicPeriod',
            new_name='academic_period',
        ),
    ]
