# Generated by Django 6.0 on 2025-12-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la période')),
                ('type', models.CharField(choices=[('PERIOD', 'Période'), ('TRIMESTER', 'Trimestre'), ('SEMESTER', 'Semestre'), ('YEAR', 'Année académique'), ('SESSION', 'Session')], default='PERIOD', max_length=20, verbose_name='Type de période')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='Période en cours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Période académique',
                'verbose_name_plural': 'Périodes académiques',
                'ordering': ['school__name', '-start_date'],
            },
        ),
    ]
