# Generated by Django 6.0 on 2025-12-13 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AcademicPeriod', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicperiod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_periods_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_periods', to='schools.school', verbose_name='École'),
        ),
        migrations.AlterUniqueTogether(
            name='academicperiod',
            unique_together={('school', 'name')},
        ),
    ]
